import type { ComplaintRow, MasterProblemRow, Priority } from "@/types";
import {
  findSimilarComplaints,
  createMasterProblem,
  getMasterProblemById,
  getMasterProblemYearSeq,
  linkComplaintToMasterProblem,
  updateMasterProblem,
  getComplaintsByMasterProblem,
} from "@/lib/db/repo";

export interface DuplicateCheckResult {
  similarComplaints: ComplaintRow[];
  masterProblemId: string | null;
  masterProblemCode: string | null;
  created: boolean;
  linkedToExisting: boolean;
}

/**
 * Detects if a new complaint is a duplicate of existing complaints
 * (same category + nearby location within 500m).
 * 
 * If 1+ similar complaints found:
 * - If they're already linked to a master problem, link new complaint to same master problem
 * - If not, create a new master problem and link all complaints to it
 * - Auto-boost priority based on complaint count
 * 
 * Returns the result with master problem info.
 */
export async function detectAndCluster(
  complaint: ComplaintRow,
  category: string,
  departmentId: string
): Promise<DuplicateCheckResult> {
  const result: DuplicateCheckResult = {
    similarComplaints: [],
    masterProblemId: null,
    masterProblemCode: null,
    created: false,
    linkedToExisting: false,
  };

  // Find similar complaints (same category, same department, within 2km)
  const similar = await findSimilarComplaints(
    category,
    complaint.latitude,
    complaint.longitude,
    departmentId,
    complaint.id,
    2 // 2km radius — covers neighbourhood-level duplicates
  );

  if (similar.length === 0) {
    // No duplicates found — this is a standalone complaint
    return result;
  }

  result.similarComplaints = similar;

  // Check if any of the similar complaints already belong to a master problem
  const existingMasterProblemId = similar.find(c => c.master_problem_id)?.master_problem_id;

  if (existingMasterProblemId) {
    // Link to existing master problem
    const masterProblem = await getMasterProblemById(existingMasterProblemId);
    if (masterProblem) {
      await linkComplaintToMasterProblem(complaint.id, existingMasterProblemId);
      
      // Update complaint count and potentially boost priority
      const allComplaints = await getComplaintsByMasterProblem(existingMasterProblemId);
      const newCount = allComplaints.length;
      const newPriority = calculatePriority(newCount);
      
      await updateMasterProblem(existingMasterProblemId, {
        complaint_count: newCount,
        priority: newPriority,
      });

      result.masterProblemId = existingMasterProblemId;
      result.masterProblemCode = masterProblem.code;
      result.linkedToExisting = true;
    }
  } else {
    // Create new master problem
    const year = new Date().getFullYear();
    const seq = await getMasterProblemYearSeq(year);
    const code = `MP-${year}-${String(seq).padStart(5, "0")}`;

    // Calculate initial priority based on number of similar complaints + 1 (new one)
    const totalComplaints = similar.length + 1;
    const priority = calculatePriority(totalComplaints);

    const masterProblem = await createMasterProblem({
      id: "", // Will be generated by createMasterProblem
      code,
      department_id: departmentId,
      district_id: complaint.district_id,
      category,
      title: `${category} — ${similar.length + 1} citizens affected`,
      description: `Multiple citizens have reported the same issue: ${complaint.description.slice(0, 200)}`,
      latitude: complaint.latitude,
      longitude: complaint.longitude,
      area: complaint.area,
      priority,
      status: "OPEN",
      assigned_employee_id: null,
      assigned_officer_id: null,
      deadline: null,
      complaint_count: totalComplaints,
      resolved_at: null,
      resolution_note: null,
      resolution_proof: null,
    });

    // Link the new complaint and all similar complaints to the master problem
    await linkComplaintToMasterProblem(complaint.id, masterProblem.id);
    for (const similarComplaint of similar) {
      await linkComplaintToMasterProblem(similarComplaint.id, masterProblem.id);
    }

    result.masterProblemId = masterProblem.id;
    result.masterProblemCode = masterProblem.code;
    result.created = true;
  }

  return result;
}

/**
 * Calculate priority based on number of complaints affected.
 * More complaints = higher priority.
 */
function calculatePriority(complaintCount: number): Priority {
  if (complaintCount >= 10) return "P0"; // Emergency — 10+ citizens affected
  if (complaintCount >= 5) return "P1";  // Critical — 5+ citizens affected
  if (complaintCount >= 2) return "P2";  // Normal — 2+ citizens affected
  return "P3"; // Low — single complaint
}
